global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'crypto_deposits_metrics'
    metrics_path: '/prometheus'
    scheme: 'http'
    static_configs:
      - targets: ['node-app:3005']  # Change this to match your Docker network setup
    params:
      blockchain: ['ethereum']
      network: ['mainnet']
      token: ['ETH']
    scrape_interval: 1m